version: '3.8'

services:
  frontend:
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
      - REACT_APP_MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN:-YOUR_MAPBOX_TOKEN_HERE}
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend

  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://uesugi_user:uesugi_password@db:5432/uesugi_heatmap
      - REDIS_URL=redis://redis:6379
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - E_STAT_API_KEY=${E_STAT_API_KEY}
      - USE_DUMMY_DATA=true
      - SECRET_KEY=${SECRET_KEY:-dev_secret_key}
    depends_on:
      - db
      - redis
    volumes:
      - ./src/backend:/app
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgis/postgis:14-3.2
    environment:
      - POSTGRES_USER=uesugi_user
      - POSTGRES_PASSWORD=uesugi_password
      - POSTGRES_DB=uesugi_heatmap
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # 開発用：pgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@uesugi.local
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    profiles:
      - dev

volumes:
  postgres_data:
  redis_data: